### ISSUE TITLE
Can't save records to new install. "DCHM" framework not found.

### ISSUE THREAD

**Issue by barnabyc** [digibib/koha-docker#10]
Hi,

After getting the build scripts working, things were looking good but my users receive "internal server error" when trying to save any records.

The logs mention `No biblionumber tag for framework "DCHM" at /usr/share/koha/lib/C4/Biblio.pm line 3093` which appears to be related to some patches in koha-docker - at least, that's the only reference to "DCHM" I could find.

Any ideas?

You've mentioned running these docker images in production, so I'm keen to get there too.

Thanks again for the help!

**Comment by bensinober** [comment]
Hi,

unfortunately we hardcoded some mysql triggers and schema overrides in our setup.

I have made this configurable as of now: GITREF b84add568b7d97a099e7d957f4c8d744c1fac1b5
so you should be able to make it work.

If using an existing db, please note you need to manually delete the triggers:
SHOW TRIGGERS;
and then delete them individually with 
DROP TRIGGER <name>;

**Comment by barnabyc** [comment]
Thanks, I see 3 triggers. I deleted `autoBiblioFrameworkCode` as that specifies the "DCHM" frameworkcode and was able to successfully add new records. I will also delete the 2 others and let you know. Thanks!

**Comment by barnabyc** [comment]
Things are working after removing those triggers, closing this issue.
