### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by mattcrum** [digibib/koha-docker#13]
Hi friends.  Great work on getting this started, however I'm having some issues still.

Getting "Internal Server Error" upon login. Basically it recognizes perfectly if I have an incorrect username/password, but when I type in a correct username and password, it spits out an "Internal Server Error" every time.  Im not sure where to go from here exactly.  Any ideas?

**Comment by bensinober** [comment]
Hi, great that you test!
some info, logs, etc. are needed to help, methinks. what image gitref do you use, or do you build your own image? `docker logs koha_build --tail 500` after crash, for example

**Comment by mattcrum** [comment]
Hey Ben! A couple things going on.  1) I failed at reading and was using the latest tag 🤦‍♂️ , and so I downloaded the most recent tag (482d3e57ca2d1d13607d061dbe59c228a477156326ae9f18a6650a11e0f9632e) and now I'm crashing with an apache config error. Logs are attached. 
[digibib-koha-apacheconf.xlsx](https://github.com/digibib/koha-docker/files/862709/digibib-koha-apacheconf.xlsx)

It's probably something simple I'm missing... not too sure. The only thing different I'm doing is reassigning ports (which typically is never a problem) since the server hosts a few different things to avoid conflict.

**Comment by bensinober** [comment]
Hi Matt,

you're missing an env var APACHE_TIMEOUT, probably others need to be set as
well. If you use docker-compose there would be automatic defaults, but if
you use docker directly, you will need to add a few ENV vars when starting
a container.

have a look at docker-compose/common.yml which sets all default ENV vars to
koha and koha_mysql

2017-03-22 21:01 GMT+01:00 Matt Crum <notifications@github.com>:

**Comment by mattcrum** [comment]
Great.  I'll keep playing with it to see what I can come up with.  I'd love to use compose but I am wanting to run this on a Synology NAS which doesn't allow for the "make" command without unofficial modding.
