### ISSUE TITLE
deichman.no repositories are broken

### ISSUE THREAD

**Issue by rfum** [digibib/koha-docker#15]
I'm trying to build project with make passes a few steps but deichman.no links breaks build session. The error messages generated by make is below :

W: Failed to fetch http://datatest.deichman.no/repositories/koha/public/dists/wheezy/InRelease  

W: Failed to fetch http://datatest.deichman.no/repositories/koha/public/dists/wheezy/Release.gpg  Unable to connect to datatest.deichman.no:http:

W: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by mtompset** [comment]
Wheezy is no longer supported for Koha, and has only been left there for those with older existing copies. Only Jessie, Stretch (Debian 8,9) and Xenial (Ubuntu 16.04 LTS) are supported. I don't believe this will be fixed.

**Comment by rfum** [comment]
Is it possible to fix that manually? I mean, like changing the repository links?

**Comment by mtompset** [comment]
Perhaps, but someone else will have to do it. And I was slightly confused, mixing up this project with kohadevbox. :)

**Comment by bensinober** [comment]
Hi, the project is migrated to gitlab now:
https://gitlab.deichman.no/digibib/koha-docker

I synced it back to github now so it is updated and the stale links mentioned above should be fixed.
