### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by jamesjessian** [digibib/koha-docker#18]
Hi, I'm hoping to experiment with Koha for the first time, so I'm trying to start up Koha on docker for the first time.

I've cloned the most recent `koha-docker` (6f9f535) and `digibib/koha` ([f04cd87](https://gitlab.deichman.no/digibib/Koha/commit/f04cd87e671bdcacacb5c98c3f18e0c5da3aa82a)) repos but I cannot login to localhost:8081 with admin/secret. I get the error "Error: Invalid username or password".

Looking at /var/log/mysql/error.log, there is an error:
```
ERROR: 1064  You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for
 the right syntax to use near 'ALTER TABLE user ADD column Show_view_priv enum('N','Y') CHARACTER SET utf8 NOT ' at line 1
180822 11:49:44 [ERROR] Aborting
180822 11:49:44  InnoDB: Starting shutdown...
```
so presumably mysql isn't running. I've searched through the source (both repos) for `show_view_priv` but can't find it mentioned. Is this a red herring? mysql should actually be running in a different container shouldn't it?

**Comment by jamesjessian** [comment]
I have checked out `release_17.11.01` of koha and that seems to be ok.

**Comment by bensinober** [comment]
Hi, latest koha-docker is highly experimental, involving a total rewrite of circulation and a new Koha Core concept, that I doubt will reach the community for quite some time... (https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=21327) .

glad if you'll be testing it though!
now the error you got seems more like a mysql permission issue. we had little success with anything after 5.6.20 with Koha so I recommend you stick to that one.

the docker-compose folder in koha-docker will give you some clues, e.g. https://github.com/digibib/koha-docker/blob/master/docker-compose/common.yml will show what mysql docker image we use.

good luck!
Benjamin

**Comment by jamesjessian** [comment]
Thanks for your reply @bensinober . My problem was solved after checking out the correct, corresponding version of koha. My bad.
An issue now is that I get a 500 error when accessing "Koha administration/Libraries and groups":
```
DBD::mysql::st execute failed: Table 'koha_name.branchcategories' doesn't exist [for Statement "SELECT `me`.`categorycode`, `me`.`categoryname`, `me`.`codedescription`, `me`.`categorytype`, `me`.`show_in_pulldown` FROM `branchcategories` `me` WHERE ( `categorytype` = ? )" with ParamValues: 0='searchdomain'] at /usr/share/perl5/DBIx/Class/Storage/DBI.pm line 1832.
```
What I'm aiming for is getting Koha up and running to try using the SIP2 protocol with it, but creating a library is the first step. But this github issue probably isn't the best place to discuss. I'll see how far I get with it and might open a new issue. Thanks for your help! 👍
