### ISSUE TITLE
Container Crashes on Restart of Server

### ISSUE THREAD

**Issue by mattcrum** [digibib/koha-docker#2]
First off, love how easy you made it to be able to start up a local Koha instance.  I pull it up with ease when I originally create the container and everything works great until I restart the system and then there's a crash that happens consistently when starting the mysql db server.  Log attached here: 
[koha-log.pdf](https://github.com/digibib/koha-salt-docker/files/40438/koha-log.pdf)

Any ideas how to get this working when the system restarts?

**Comment by bensinober** [comment]
Thanks! Docker is a real opportunity once you learn how to use it. Nothing obvious from the logs, but you might be struck by some koha mysql bugs appearing in v5.6.22 and beyond. New strict mode default makes koha bugs fatal. Koha bug 13523 among others. Try to pin your mysql to 5.6.21 and see if problem persists

**Comment by bensinober** [comment]
Closing this as setup is now highly changed. Please open new issue if problem persists.
