### ISSUE TITLE
Can't start up with docker-compose

### ISSUE THREAD

**Issue by jlegido** [digibib/koha-docker#20]
Hi there.

First of all many thanks for your time.

Since it's my first interaction with docker koha maybe I didn't follow the right steps.

### Steps to reproduce:

1. Clone repo:

`git clone https://gitlab.deichman.no/digibib/koha`

2. Clone repo

`git clone https://gitlab.deichman.no/digibib/koha-docker`

3. Try to bring up a development environment with docker-compose:

```
cd koha-docker/docker-compose
source docker-compose.env && KOHAPATH=.. docker-compose -f common.yml -f dev.yml build koha_dev
```
### Expected behaviour:

See the docker-compose logs indicating that all containers are started up

### Found behaviour:

Below error:

```
...
Step 16/33 : ENV QATOOLS_REPO https://github.com/Koha-Community/qa-test-tools.git
 ---> Running in 9b8d58f8f0d3
Removing intermediate container 9b8d58f8f0d3
 ---> a3f2eff22cf7
Step 17/33 : RUN DEBIAN_FRONTEND=noninteractive apt-get update &&     sudo apt-get install -q -y cpanminus vim net-tools git-email telnet screen wget less curl htop &&     apt-get clean
 ---> Running in 620e1be14370
Ign http://static.deichman.no wheezy InRelease
Get:1 http://debian.koha-community.org unstable InRelease [4568 B]
Get:2 http://debian.koha-community.org stable InRelease [4565 B]
Get:3 http://security.debian.org jessie/updates InRelease [44.9 kB]
Ign http://static.deichman.no wheezy Release.gpg
Ign http://deb.debian.org jessie InRelease
Get:4 http://static.deichman.no wheezy Release [2694 B]
Get:5 http://deb.debian.org jessie-updates InRelease [7340 B]
Get:6 http://static.deichman.no wheezy/main amd64 Packages [190 kB]
Hit http://deb.debian.org jessie Release.gpg
Hit http://deb.debian.org jessie Release
Get:7 http://debian.koha-community.org unstable/main amd64 Packages [20.8 kB]
Get:8 http://debian.koha-community.org stable/main amd64 Packages [19.1 kB]
Get:9 http://security.debian.org jessie/updates/main amd64 Packages [825 kB]
Get:10 http://deb.debian.org jessie/main amd64 Packages [9098 kB]
Fetched 10.2 MB in 42s (238 kB/s)
W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/InRelease  Unable to find expected entry 'main/binary-amd64/Packages' in Release file (Wrong sources.list entry or malformed file)

E: Some index files failed to download. They have been ignored, or old ones used instead.
ERROR: Service 'koha_dev' failed to build: The command '/bin/sh -c DEBIAN_FRONTEND=noninteractive apt-get update &&     sudo apt-get install -q -y cpanminus vim net-tools git-email telnet screen wget less curl htop &&     apt-get clean' returned a non-zero code: 100
```

**Comment by brinxmat** [comment]
I was playing about with this, cloned from deichman's gitlab. Take a look at the PR https://github.com/brinxmat/koha-docker/pull/1 and see if this helps (I guess you will need to rebuild Koha docker image and change the KOHA_BASE_IMAGE_TAG accordingly in the docker-compose/docker-compose.env)

**Comment by bensinober** [comment]
as @brinxmat points out, it is a debian repo issue, so his fix is all good!

Beware that we strayed away from the community version of Koha and this repo is soon deprecated. We moved all code into a new project (https://gitlab.deichman.no/digibib/deichman) where koha+mysql is just a part that still work standalone. Note that it is a _heavily_ rewritten and customized version of Koha (new auth, new circulation, new api, etc.)

If you want to test a dockerized community version, there is not so much to choose from, but you can test the ones at https://hub.docker.com/u/koha 
Hopefully someone might grab this repo and continue developing a community version or start a new one.

btw, if you still want to use debian jessie, you can have a look at the patch we use: https://gitlab.deichman.no/digibib/deichman/commit/47cc0d067be26a041be295885a24b8148292f8d4
