### ISSUE TITLE
How to set up a container with your dockerfile not clear for a beginner

### ISSUE THREAD

**Issue by edipretoro** [digibib/koha-docker#3]
Hi,

I'm quite new with docker, so I guess the problem is more of a comprehension problem than a real bug. So I'm trying to set up a docker container based on your work, unfortunately, that didn't work well for me. I'm trying to understand what the « [tag/revision] » mean in « digibib/koha:[tag/revision] »! I know, it must seem obvious for you, but for me, it's quite obscure;
- I can't see any tag on your git repository;
- I've tried the docker command (docker run --interactive --name koha_docker -p 6001:6001 -p 8080:8080 -p 8081:8081 -t) with the following tags:
  - « digibib/koha:3.22.01 »
  - « digibib/koha:[3.22.01] » 
  - « digibib/koha:98eef6f »
  - « digibib/koha:[98eef6f] »

Can you tell me what is the exact syntax? 

Thanks in advance!

Emmanuel Di Pretoro

**Comment by brinxmat** [comment]
Your command works fine, but you need to use a full uuid for the git revision you want to use (e.g. "98eef6f99ea4d799e7bc8a3a41c1488f466026dc")

```
sudo docker run --interactive --name koha_docker -p 6001:6001 -p 8080:8080 -p 8081:8081 -t digibib/koha:98eef6f99ea4d799e7bc8a3a41c1488f466026dc
```

**Comment by edipretoro** [comment]
Thanks for your really quick answer and sorry for this silly question! The container is now building!
