### ISSUE TITLE
Problem with run_webinstaller.pl?

### ISSUE THREAD

**Issue by edipretoro** [digibib/koha-docker#4]
The container is now running, but I can't access to Koha (either the OPAC or the intranet). I get a code 500 (Internal Server Error). When I check the logs, I can see the following in red:

>    ID: run_webinstaller
>    Function: cmd.script
>    Result: False
>    Comment: 
>    Started: 12:21:45.371069
>    Duration: 366.781 ms
>    Changes:   

What am I missing?

**Comment by bensinober** [comment]
Hi!
glad you deside to test our koha setup.

Actually all You need is to setup user and pass in pillar/ admin.sls or
just copy the example file.

Benjamin

user søndag 10. januar 2016 skrev Emmanuel Di Pretoro <
notifications@github.com> følgende:

**Comment by edipretoro** [comment]
Yes, I hope to be able to find an easy to let my students install by themselves Koha. So, VM are a way to do it, and docker is another one. 

Can you describe me how I can actually make this modification? Do I need to connect to the docker container to make some modifications? Do I need to fork your repository and push the modifications on it and after that create a new container?

I'm quite new with docker and that explain my questions! 

Thanks in advance for your time!

**Comment by edipretoro** [comment]
Here is a larger view of the log:

> Total states run:     8
> [INFO    ] Loading fresh modules for state activity
> [INFO    ] Fetching file from saltenv 'base', *\* done *\* 'koha/webinstaller.sls'
> [INFO    ] Running state [/usr/local/bin/KohaWebInstallAutomation.pl] at time 17:06:30.906993
> [INFO    ] Executing state file.managed for /usr/local/bin/KohaWebInstallAutomation.pl
> [INFO    ] Fetching file from saltenv 'base', *\* done *\* 'koha/files/KohaWebInstallAutomation.pl'
> [INFO    ] File changed:
> New file
> [INFO    ] Completed state [/usr/local/bin/KohaWebInstallAutomation.pl] at time 17:06:30.919937
> [INFO    ] Running state [run_webinstaller] at time 17:06:30.921982
> [INFO    ] Executing state cmd.script for run_webinstaller
> [INFO    ] Fetching file from saltenv 'base', *\* done *\* 'koha/files/updatekohadbversion.sh'
> [INFO    ] Executing command '/usr/share/koha/lib/tmpmEul_H.sh' in directory '/usr/share/koha/lib'
> [ERROR   ] No changes made for run_webinstaller
> [INFO    ] Completed state [run_webinstaller] at time 17:06:31.294295
> 
> ## local:
> 
> ID: /usr/local/bin/KohaWebInstallAutomation.pl
> Function: file.managed
> Result: True
> Comment: File /usr/local/bin/KohaWebInstallAutomation.pl updated
> Started: 17:06:30.906993
> Duration: 12.944 ms
> 
> ## Changes:   
> 
> diff:
> New file
> mode:
> 
> ## 0644
> 
> ID: run_webinstaller
> Function: cmd.script
> Result: False
> Comment: 
> Started: 17:06:30.921982
> Duration: 372.313 ms
> Changes:   
> 
> ## Summary
> 
> Succeeded: 1 (changed=1)
> Failed:    1

So the problem seem to be that no changes are made for this section (`[ERROR   ] No changes made for run_webinstaller`).

**Comment by brinxmat** [comment]
Did you try Bensinober's suggested solution? (Basically, rename https://github.com/digibib/koha-salt-docker/blob/master/pillar/koha/admin.sls.example as "admin.sls")

**Comment by bensinober** [comment]
Depending on your setup, if you only want to test, you have two options:
- if you're running linux, you can download and run a docker image directly. Read the README in this repo for examples. Basically you'll just:

```
docker run -d --name koha_docker \
    -p 6001:6001 -p 8080:8080 -p 8081:8081 \
    -t digibib/koha
```

and in a little while you'll have Koha running on ports 8080(opac) and 8081(intra) with default admin/secret credentials
- anything else, you would be best off to run a VM. We recommend using Vagrant and just spin up the default box in this repo with `make` (same credentials as above)

**Comment by edipretoro** [comment]
@brinxmat Yes, I dit connect myself to the docker container and a `admin.sls`file was present in the `/srv/pillar/koha/` directory. And it was the same as the `admin.sls.example` file you link.

@bensinober I'm running on Linux (Ubuntu 15.10) and my docker command was `sudo docker run --interactive --name koha_docker -p 6001:6001 -p 8080:8080 -p 8081:8081 -t digibib/koha:98eef6f99ea4d799e7bc8a3a41c1488f466026dc` (as mentioned in a previous ticket: https://github.com/digibib/koha-salt-docker/issues/3). I've currently created a new container with your docker command but I still have the same error.

**Comment by bensinober** [comment]
Closing this as setup is now highly changed. Please open new issue if problem persists.
