### ISSUE TITLE
500 error after running the docker container

### ISSUE THREAD

**Issue by cduverne** [digibib/koha-docker#6]
Hello, I followed both installation methods, in vagrant or standalone on my machine, basically : 
- Docker pulled latest build
- `docker run -d --name koha_docker     -p 6001:6001 -p 8080:8080 -p 8081:8081     -t kohaimage:latest`

When the container runs, I try to log on 192.168.33.10:8080 or 8081 (Which is the IP of the Vagrant Box), and I get a 500 error.

Could you help me please ?

**Comment by bensinober** [comment]
hi @cduverne , actually we're not using automated builds in docker hub, so digibib:koha:latest would not be the latest. Rather we build and tag images continuously from git refs from the master bramch of this repo. So the latest as I write this is digibib:koha:fe360b67a4e314f91a12f4fbc5587e7ac6a37061 

You can see the freshest images here: https://hub.docker.com/r/digibib/koha/tags/

If you tail the logs of the container with `docker logs -f` you should get an idea what is wrong. Also you will be able to see the setup of Koha as it proceeds. It will probably take up to ten seconds to set up a fresh db.

Depending of your knowledge of docker, you can start with 
`https://github.com/digibib/koha-docker/blob/master/Dockerfile`
which is the build of the image and displays some ENV variables that can be overridden when starting a new container.
`https://github.com/digibib/koha-docker/blob/master/docker-entrypoint.sh` is the ENTRYPOINT run when starting the container, which basically sets up Koha by populating the db and running the webinstaller, and then starting the various koha services.

In case you want to build koha yourself, have a look at the Makefile and the docker-compose templates. If you run vagrant, you should be ok with `KOHAENV=build make provision` for sensible defaults. If you run docker on your machine (recommended), you would do `NOVAGRANT=true KOHAENV=build make provision`.

Please don't hesitate to ask, and pass along failing logs.

**Comment by cduverne** [comment]
Thanks for your assistance !

I also tried with the latest build, and arrive at the same problem.

I'm seeing this in the docker logs : 

> Running webinstaller - please be patient ...
> ERROR 1146 (42S02) at line 1: Table 'koha_name.systempreferences' doesn't exist
> ERROR 1146 (42S02) at line 1: Table 'koha_name.marc_tag_structure' doesn't exist
> Smartmatch is experimental at /installer/KohaWebInstallAutomation.pl line 96.
> Smartmatch is experimental at /installer/KohaWebInstallAutomation.pl line 96.
> Smartmatch is experimental at /installer/KohaWebInstallAutomation.pl line 102.
> Request failed. URI: WWW::Mechanize=HASH(0x1ac2b20)->response()->headers()->{location} at /installer/KohaWebInstallAutomation.pl line 73.
>  at /installer/KohaWebInstallAutomation.pl line 73.
>   KohaWebInstallAutomation::test_response_code(KohaWebInstallAutomation=HASH(0x1081720)) called at /installer/KohaWebInstallAutomation.pl line 38
>   KohaWebInstallAutomation::init(KohaWebInstallAutomation=HASH(0x1081720), "uri", "http://127.0.0.1:8081/", "user", "admin", "pass", "secret") called at /installer/KohaWebInstallAutomation.pl line 21
>   KohaWebInstallAutomation::new("KohaWebInstallAutomation", "uri", "http://127.0.0.1:8081/", "user", "admin", "pass", "secret") called at -e line 1
> 
> changed=yes comment="" instance=name           newdbversion="16.0600010" olddbversion=""

The full logs are attached.
Thanks again

[cont_logs_koha_docker.txt](https://github.com/digibib/koha-docker/files/405055/cont_logs_koha_docker.txt)

**Comment by bensinober** [comment]
Hi,
actually, you experience mysql and apache in docker restrictions, so you need to add --cap-add=DAC_READ_SEARCH to the run command. We also recommend SYS_NICE and MKNOD for proper working services through sockets.

Please try:

```
docker run --rm --cap-add=DAC_READ_SEARCH --cap-add=SYS_NICE --cap-add=MKNOD --name koha_docker -p 6001:6001 -p 8080:8080 -p 8081:8081 -t digibib/koha:ea5c913a48de333a8b33f692809d3383b8b95fa7
```

to run our latest image, and you will hopefully see the logs as the installer proceeds and get a working koha.

I will update the documentation to reflect this.

**Comment by cduverne** [comment]
Great ! It worked !!

Unfortunately, I can't create a patron category, I opened a bug at Koha : https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=17069 

Thanks a lot for you help.
