### ISSUE TITLE
Should this be used in production?

### ISSUE THREAD

**Issue by foobarable** [digibib/koha-docker#7]
Should this repo be used in production or is this purely for developing purposes? How do you do upgrades and database migrations?

**Comment by foobarable** [comment]
I could find the answer by myself:

It seems this is used in an production environment. 

Source: http://digital.deichman.no/blog/2015/01/12/working-with-koha-at-oslo-public-library/

**Comment by bensinober** [comment]
Hi, thanks for your interest!

Actually it has been production ready for a while, but we will have an official launch in about a month. It is part of a larger setup with docker compose and docker containers including elasticsearch, fuseki and self-produced patron interface and cataloguing tools. The main metadata repository is moved out of Koha to a RDF store and a service which propagates the neccessary data for Koha to work as a circulation system. We believe firmly that Koha and its MARC-centric bibliographic system is insufficient for providing and presenting modern library metadata.

The full project is at https://github.com/digibib/ls.ext (library system extended), but in short, it is mainly isolated microservices in a docker network. Mysql and the database, for instance, are separate containers and volumes that are easily exchanged.

Upgrading in production is as easy as switching containers, yet, of course, as long as db upgrade between koha versions work.

Please get in touch if you have more questions!
Benjamin
Oslo Public Library
