### ISSUE TITLE
Koha requires mpm_itk

### ISSUE THREAD

**Issue by danmichaelo** [digibib/koha-docker#8]
Got this error from`fd88134`:

```
koha          | Koha requires mpm_itk to be enabled within Apache in order to run.
koha          | Typically this can be enabled with:
koha          |
koha          |     sudo a2enmod mpm_itk
koha          |
koha exited with code 1
```

Rolled back to `fe360b6` (last commit 16 days ago) and the error disappeared. Didn't try the commits in-between. Have you run into this?

**Comment by bensinober** [comment]
Hi,
depends on how you setup/start your environment? Do you use plain docker or
docker-compose? We recommend the latter as it makes configuration much
easier.

sounds like it crashes on apache restart in the docker-entrypoint?
Anyways the mpm_itk is standard as from ubuntu 16.04 so this should not be
a problem. Perhaps
the error is somewhere else in your log?

2017-01-04 22:41 GMT+01:00 Dan Michael O. Heggø <notifications@github.com>:

**Comment by danmichaelo** [comment]
Turned out to be [this test](https://github.com/Koha-Community/Koha/blob/474a369fc03f992971c8af11c910f778e34ac9b9/debian/scripts/koha-create#L148) in `koha_create` failing because of invalid Apache config, caused by `APACHE_TIMEOUT` not being defined.

```
The apache2 configtest failed. ... (warning).
Output of config test was:
AH00526: Syntax error on line 4 of /etc/apache2/sites-enabled/sonen.conf:
Timeout takes one argument, Timeout duration (sec)
Action 'configtest' failed.
The Apache error log may have more information.
```

After extending my `docker-compose.yml` with more of the environment variables from https://github.com/digibib/koha-docker/blob/master/docker-compose/common.yml , everything worked again :)
