### ISSUE TITLE
Can't login to new instance

### ISSUE THREAD

**Issue by barnabyc** [digibib/koha-docker#9]
Using the docker hub tag from 6 days ago (Jan 26th, 2017) `f40814710e2bd38c26366fb6ec3c3aba0c882406` I was able to get a koha container running and connected to an external mysql container. The automated webinstaller seemed to run fine when I tail the koha container logs, and both OPAC and Intra respond on 8080 and 8081.

Now I need to login, but `admin` / `secret` isn't working - simply says I've entered an incorrect username or password.

What are the default creds when using the docker image?

Thanks! Great project, looking forward to deploying to production!

PS. The more recent docker hub tags from 2 days ago weren't working. I tried several, but none could connect to mysql despite using the same `-e` docker args that worked for the latest tag from 6 days ago.

**Comment by bensinober** [comment]
Hi,

not sure what you mean by 6 days ago:
https://github.com/digibib/koha-docker/commit/f40814710e2bd38c26366fb6ec3c3aba0c882406
is from Sept 2016 so I would not expect that to work

actually, there is a bug fixed in develop lately which tries to fix a bug in templates, but erroneously expects Norwegian template to exist. A bypass until we push a fix is to add nb-NO to INSTALLED_LANGUAGES env

or in docker-compose/.env if using docker-compose (recommended)
INSTALLED_LANGUAGES=nb-NO (you can add more space-separated)

**Comment by barnabyc** [comment]
That's odd, Docker Hub shows "6 days ago" next to that tag: https://cl.ly/151I1m1R3u31

I wasn't using Compose but will certainly try it out with that flag later today and reply. Assuming the correct template is present, will `admin` / `secret` be correct default creds to use?

Thanks for the response @bensinober.

**Comment by bensinober** [comment]
Yes, I'm not entirely sure how docker deals with tags and timestamps on
push. It seems to update every layer that is pushed, or perhaps it is our
jenkins CI messing this up.

latest tag (now in production) is
9b3c401bb0451cca4bb004efd62ef02a778d16a8 (31.jan)

and before that
545150d9f05a09ca778c8afa6094f7da187a2416 (27.jan)

we will try to use git tags in time for easier access, and update our
documentation

admin/secret is the intra/mysql user/pass by default, unless
koha_mysql already is populated.

api/secret is the default KOHA RESTFUL api user/pass

PS: you could easily build your own image, if you want, by checking out our repo
https://github.com/digibib/koha-docker

`make provision && make rebuild`

will build an image from the current GITREF you are at. You can even
checkout develop branch
(which includes the latest fixes including INSTALLED_LANGUAGES) and
build from there


2017-02-02 18:25 GMT+01:00 Barnaby Claydon <notifications@github.com>:

**Comment by barnabyc** [comment]
Ok, I got images built using HEAD of develop.

I did have to change docker-compse/common.yml on line 33:
```
INSTALL_LANGUAGES: "${INSTALL_LANGUAGES:-}"
```
to
```
INSTALL_LANGUAGES: "${INSTALL_LANGUAGES:-en}"
```
As I could not get either `docker-compose/.env` or regular `export INSTALL_LANGUAGES` to pick-up the `en`.

I'm curious why the docker-compose/common.yml does not expose OPAC on 8080:8080? Do you prefer to have a separate http server container linked?

Thanks again for the help.

**Comment by bensinober** [comment]
Actually, you could just add 8080:8080 to the ports section if you need it.
We don't use the Koha opac, but our own-made.

Benjamin

2017-02-03 5:46 GMT+01:00 Barnaby Claydon <notifications@github.com>:

**Comment by barnabyc** [comment]
Yes, that's what I did. I'm curious to hear about your own-made one though, if that's public.

Closing this issue now as login is definitely working, thanks again for the help!
